// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMSC2240Finals.Models
{
    public partial class Customers
    {
        public Customers()
        {
            Invoice = new HashSet<Invoice>();
            Vehicles = new HashSet<Vehicles>();
        }

        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}