// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMSC2240Finals.Models
{
    public partial class Employees
    {
        public Employees()
        {
            Invoice = new HashSet<Invoice>();
        }

        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public decimal? HourlyWage { get; set; }

        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}