// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMSC2240Finals.Models
{
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public DateTime Date { get; set; }
        public int EmployeeId { get; set; }
        public int CustomerId { get; set; }
        public int ServiceId { get; set; }
        public decimal Price { get; set; }

        public virtual Customers Customer { get; set; }
        public virtual Employees Employee { get; set; }
        public virtual Services Service { get; set; }
    }
}