// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMSC2240Finals.Models
{
    public partial class Services
    {
        public Services()
        {
            Invoice = new HashSet<Invoice>();
        }

        public int ServiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}