// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMSC2240Finals.Models
{
    public partial class Vehicles
    {
        public int VehicleId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string Vin { get; set; }
        public int CustomerId { get; set; }

        public virtual Customers Customer { get; set; }
    }
}